name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: node build.js
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./site"
      - name: Deploy
        uses: actions/deploy-pages@v4
